name = "discovery-hidden-japan"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production.vars]
# Environment variables will be set in Cloudflare dashboard
# RESEND_API_KEY = "your-resend-api-key"